language: cpp
os: [linux, osx]

env:
  matrix:
    - BUILD_TYPE=Debug   CFLAGS=-m32 CXXFLAGS=-m32
    - BUILD_TYPE=Debug   CFLAGS=-m64 CXXFLAGS=-m64
    - BUILD_TYPE=Release CFLAGS=-m32 CXXFLAGS=-m32
    - BUILD_TYPE=Release CFLAGS=-m64 CXXFLAGS=-m64

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - [cmake, valgrind, gcc-multilib, g++-multilib, g++-4.9, g++-5, g++-6, g++7]
      env:
        - BUILD_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
        - BUILD_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
        - BUILD_EVAL="CC=gcc-5 && CXX=g++-5"
        - BUILD_EVAL="CC=gcc-6 && CXX=g++-6"
        - BUILD_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode7.3
      env:
        - BUILD_EVAL=""
    - os: osx
      osx_image: xcode8
      env:
        - BUILD_EVAL=""
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_EVAL=""

before_install:
  - eval "${BUILD_EVAL}"

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      echo PREV_CMAKE `cmake --version`
      CMAKE_PACKAGE="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
      mkdir -p deps/cmake
      wget --no-check-certificate --quiet -O - ${CMAKE_PACKAGE} | tar --strip-components=1 -xz -C deps/cmake
      export PATH=${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}
    else
      brew update
      brew outdated cmake || brew upgrade cmake
    fi

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DASMJIT_BUILD_TEST=1
  - cd ..

script:
  - cd build
  - make
  - cd ..

  - ./build/asmjit_test_unit
  - ./build/asmjit_test_opcode > /dev/null
  - ./build/asmjit_test_x86_asm
  - ./build/asmjit_test_x86_cc

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_unit; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_x86_asm; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./build/asmjit_test_x86_cc; fi;
